### ISSUE TITLE
SSL support with letsencrypt

### ISSUE THREAD

**Issue by goegol** [dennissiemensma/dsmr-reader#157]
Hi,

Maybe an idea:
SSL support for the webinterface with letsencrypt?

**Comment by dennissiemensma** [comment]
Hi! Thank you for your suggestion! It's actually a very good one as well, but I'm afraid this isn't possible due to technical limits.

* First of all, it's not possible to issue certificates on private networks, like the one at peoples home. And that the main environment for this project to live. (https://community.letsencrypt.org/t/certificates-for-hosts-on-private-networks/174)

* Secondly, if I want to support this for public networks (for those running or exposing their application to the internet), then the application would also need some logic to support the domain validation. Besides, in order to control the web server (Nginx by default) serving the certificate, the application would need `root` access, something I prevented in the installation instructions.

* And last, you would need to have a public accessible domain, to have Let's Encrypt validate you as an owner of the domain used for the certificate. Most hobbyists are just running this at home in their private network.

However, if you do have a (public) domain available and pointed to your installation, exposed to the internet, you might want to try Certbot for Let's Encrypt. They have pretty good instructions available as well: https://certbot.eff.org/

I you need anymore  hints or help feel free to ask.
