### ISSUE TITLE
Display error compare page on mobile

### ISSUE THREAD

**Issue by thommy101** [dennissiemensma/dsmr-reader#276]
Hi,

The compare page on mobile has some weird display errors with the time range selection. They are hard to select. They are diagonally placed and the day and month have there hit box to low. This is also reproducible on desktop when resizing the window to anything smaller than 1000 px.

A possible fix I've found is removing the float of .sm-st-icon (around line 3744 of style.css) and letting the col-md do it's work.

**Comment by dennissiemensma** [comment]
Hi thank you for reporting this issue and the detailedinformation. I will look into this in a future release dedicated to UI fixes.

**Comment by dennissiemensma** [comment]
This was caused by the responsive **row** elements used. It seems that the **columns** containing the three buttons are converted to **rows** when the screen is too small. And because the div's of the buttons did not have any height, they were aligned weirdly.

I've fixed this by giving them all a fixed height. The 'mobile view' will now show them on top of each other, allowing the hitbox to be normal again as well. See below for a screenshot, thanks again for reporting.

![screenshot from 2017-09-29 20-48-08](https://user-images.githubusercontent.com/16581744/31031128-17b7f5ea-a558-11e7-8e19-9e8894e51980.png)
